version: '3'

tasks:
  run:
    - set -a && source .env && set +a && winpty python3 src/main.py

  init:
    - git submodule update --init --recursive
    - sqlite3 db.db < sql/init.sql
    - (cd src/balaboba; go build cmd/*.go && mv cmd.exe ../../balaboba.exe)
    # TODO: download dataset and build model

  linter:
    - flake8 *.py commands/*.py --max-line-length 120 --ignore=E302,E305

  get_chat_logs:
    generates: [dataset]
    cmds:
      - tcd -q --channel screamlark --first 10
      - cat *.txt | rg -v 'StreamElements' | cut -d' ' -f3- > logs
      - cat dataset logs | rg -v '(!(g|say)|Продолжай кормить рыбку!|ставки|^\d{1,3} \d{1,3}$)' | sort -u > tmp_dataset
      - mv tmp_dataset dataset
      - rm logs

  train:
    deps: [get_chat_logs]
    sources: [dataset]
    generates: [model.json]
    cmds:
      - python quotes_generator/main.py train --dataset dataset --model model.json

  commit:
    - venv/Scripts/pip freeze > requirements.txt
    - task: linter
    - cmd: git add .
      ignore_error: true
    - git status
    - cmd: git commit -m "Autocommit"
      ignore_error: true

  push_heroku:
    - git push heroku master

  push_github:
    - git push github master

  push:
    deps:
      - push_heroku
      - push_github

  deploy-fix:
    - task: commit
    - task: push

  deploy:
    - task: train
    - task: deploy-fix

