version: '3'

tasks:
  get_chat_logs:
    generates: [dataset]
    cmds:
      - tcd -q --channel screamlark --first 10
      - cat *.txt | grep -v 'StreamElements' | cut -d' ' -f3- | grep -v '!g' > logs
      - cat dataset logs | grep -v 'ставки' | sort -u > tmp_dataset
      - mv tmp_dataset dataset
      - rm *.txt logs

  train:
    deps: [get_chat_logs]
    sources: [dataset]
    generates: [model.json]
    cmds:
      - python quotes_generator/main.py train --dataset dataset --model model.json

  commit:
    - venv/Scripts/pip freeze > requirements.txt
    - cmd: git add *
      ignore_error: true
    - git status
    - cmd: git commit -m "Autocommit"
      ignore_error: true

  deploy-fix:
    - task: commit
    - git push heroku master

  deploy:
    - task: train
    - task: deploy-fix

