name: Push docker image to github registry

on:
  push:
    branches: [ "master" ]

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Login to Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: true
          tags:
            - ghcr.io/rprtr258/twitch-bot:latest
            - ghcr.io/rprtr258/twitch-bot:${{ github.sha }}
